### ISSUE TITLE
config.scrub_fields is applied to config.person?

### ISSUE THREAD

**Issue by drjayvee** [rollbar/rollbar-php#180]
We recently switched from 0.x to 1.1.1 and noticed that new issues have "******" as their person.username.

Consider this config:
```
'scrub_fields' => ['username', 'password'],
'person' => ['id' => 123, 'username' => 'One Two Three']
```
I suspect that `config.scrub_fields` is applied to `config.person`, causing `person.username` to be scrubbed when an error is logged.

I would propose that `person` data be ignored by the scrubber.

**Comment by rokob** [comment]
There is a bit of tradeoff here so it isn't exactly obvious what one should do. We want to scrub the entire payload based on the scrub_fields configuration, special casing the person data will quickly lead to the opposite issue where people will be surprised that the password that they didn't strip out of their user object is not being scrubbed.

One workaround is to use a custom transform to add the person data to the payload after scrubbing has been done, there are examples in the README about how to add these transform functions.

Additionally, it is a bit odd to scrub username generally, but want it in the one case where it probably shows up which is in the person field. We could add an option for a configurable whitelist of keys to ignore scrubbing if we are nested under that key, but this opens other doors.

I think the easiest fix might just be to have an extra configuration option to ignoring scrubbing for the person data which defaults to false so that if that is what you want you can turn it on, but which most people will not want to do.

**Comment by drjayvee** [comment]
Thanks for your detailed reply.

I agree that it's a tradeoff. Maybe the best way forward is to keep the functionality as is but document this? The documentation about `scrub_fields` should probably mention that it's best not to include `username` (or any other `person` keys).

As for my particular problem: I'll go for an easy workaround: using something other than `username` in the login form.

**Comment by ArturMoczulski** [comment]
This is ready for review in https://github.com/rollbar/rollbar-php/pull/216
