### ISSUE TITLE
Add buffering functionality

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-php#196]
The previous version of rollbar-php (0.18.2) would batch send messages. This version sends messages when they are received. In the case of a severe error, many messages will be logged one after another. Is there any plan to restore the batched messages?

**Comment by coryvirok** [comment]
Buffering is a good idea. We have this implemented in some of the other SDKs but it's all client-side. We aren't planning on supporting the batch endpoint on the server-side any longer. However, we can support buffering up a configurable # of messages and a maximum amount of time to buffer in the SDK. 

If you just want the ability to send data in batches, I would recommend looking at the [rollbar-agent](https://github.com/rollbar/rollbar-agent) to handle this. That's going to be the most performant method and will not require any SDK changes.

**Comment by unix1** [comment]
Hello @and-megan @coryvirok - thank you for helping. Just to be explicit in changes from 0.x to 1.x:

In 0.x branch:
- events were sent using [register_shutdown_function](https://secure.php.net/manual/en/function.register-shutdown-function.php) callback function which executes after php has completed processing and before the process is shut down
- events were batched by default so only 1 HTTP connection was required to send many (up to configured number of) events

In 1.x branch:
- events are sent inline as they occur during the execution of the script
- events are no longer batched (and batching is being deprecated), so for `n` events `n` separate `curl` HTTP calls will be made to rollbar's serice

I'm wondering if I'm missing anything because these 2 changes seem counter-intuitive from the performance perspective, also noting that [Rollbar status](http://status.rollbar.com/) page reports that average api.rollbar.com response time is >500ms with common spikes up to 1s and higher. Buffering on its own wouldn't address the above 2 issues.

During the normal operation, when we log low number of debug/info/warning/error/critical events, this would still have significant impact on our application performance. But worse, during times when we are experiencing problems and send more events than normal, we could end up compounding effects of an already degraded performance.

Am I missing something, or is there a plan to address this outside of using the rollbar agent? Thank you!

**Comment by coryvirok** [comment]
Thanks for the feedback! I defer to @rokob on the technical parts.

**Comment by rokob** [comment]
I basically did this in https://github.com/rollbar/rollbar-php/pull/217 as part of the work on performance, I will update you with the details once that is finalized.

**Comment by unix1** [comment]
Excellent! Thank you for following up.
