### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-php#246]
Internal discussion in https://app.clubhouse.io/rollbar/story/25182/get-magento-2-to-work-with-rollbar

**Comment by rokob** [comment]
The desired end goal is to: "override the default Magento Stream Handlers with the Stream Handler for Monolog that we provide. There definitely is a lack of "plug-and-play" information and support for Magento 2 with Rollbar"

For Magento 1, there is an Airbrake workaround which works: https://github.com/airbrake/Airbrake-Magento except for front end error reporting

This might not need any code, but could just be a documentation on best practices for integration of Rollbar with Magento 2.

**Comment by rivkahstandig3636** [comment]
@rokob Is this a docs issue or is a code change needed?

**Comment by joostvanveen** [comment]
Documentation on how to use Rollbar in Magento 2 would be very welcome. 

We find that Rollbar is not catching any errors from magento 2, other than straightforward PHP errors in a phtml template file. All other exceptions, errors, warnings and notices are not logged to Rollbar. 

Being able to log Magento errors and exceptions to Rollbar is particularly important to us because Magento 2's own error logging leaves a lot to be desired.

The problem is probably due to namespacing issues, but we are not sure how to tackle those. At the moment, we initialise it the same way as we do in all other applications, in the application's entry point, in this case index.php.

```
use \Rollbar\Rollbar;
use \Rollbar\Payload\Level;

// [...]

$config = array(
        'access_token' => C_ROLLBAR_TOKEN,
        'environment' => C_ENVIRONMENT,
        'root' => $_SERVER['DOCUMENT_ROOT']
    );
    Rollbar::init($config, false, false);
```

Rollbar test notifications only show up in Rollbar when we use the fully qualified classnames for Rollbar and Level, e.g.
```
\Rollbar\Rollbar::log(\Rollbar\Payload\Level::ERROR, 'Test error');
```

Normal use throws a 500 error:
```
Rollbar::log(Level::ERROR, 'Test error');
```

**Comment by ArturMoczulski** [comment]
Integration with Magento2 will require building a Magento Rollbar module. Magento2 has its' own way of handling exceptions and errors which effectively disables Rollbar's handlers set up through `Rollbar::init`.

I added an issue for starting the work on a Magento Rollbar Module here: https://github.com/rollbar/rollbar-php/issues/333
