### ISSUE TITLE
Log->error($e) has different info than throw the exception and let error_reporting handle it

### ISSUE THREAD

**Issue by monteiro** [rollbar/rollbar-php#275]
I'm currently using monolog and new relic handler:

```php 
Rollbar::init($rollbarConfiguration);
$logger->pushHandler(new PsrHandler(Rollbar::logger()));
```

When I try to log the exception using:

```php
try {
 //something that throws an exception
} catch (\Exception $ex) {
  $this->logger->error($e);
}
```

The exception trace doesn't have any colors and it is different than letting rollbar **error_reporting** to handle the exceptions (without catching the exception).

If I throw the exception without catching it, the result is a more complete exception trace w/ colors.

It looks like when error_reporting catches the exception, it executes the **DataBuilder** to fill the log with more info.

**Comment by ArturMoczulski** [comment]
Hey @monteiro 

This is a result of using `PsrHandler` instead of `RollbarHandler`. Unfortunately, it is the best thing you can do as of right because `RollbarHandler` is heavily outdated and doesn't work with our latest releases.

I submitted a PR to Monolog repo long time ago with code changes to update `RollbarHandler`, but they still have not processed my PR. In meantime, I suggest you look into using this Mononolog PR: https://github.com/Seldaek/monolog/pull/1042

More details on `PsrHandler`:
`PsrHandler::handle` on line 52 packs the Exception object into `$record['message']` and converts it to a string
```php
$this->logger->log(strtolower($record['level_name']), $record['message'], $record['context']);
```
This way the Exeception object is passed to `RollbarLogger::log` as a string and formatted in the JSON payload as a message instead of an Exception object.

**Comment by ArturMoczulski** [comment]
Long story short this is the same issue as https://github.com/rollbar/rollbar-php/issues/249

**Comment by mente** [comment]
Context `exception` is part of PSR-3 so why not add support of it directly into `RollbarLogger` rather than waiting for others to update their library?

**Comment by monteiro** [comment]
Thanks @ArturMoczulski for the effort.
