### ISSUE TITLE
Confusing stack traces due to missing filename/lineno

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-php#292]
Consider this code:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
error_reporting(E_ALL);

use \Rollbar\Rollbar;
use \Rollbar\Payload\Level;

$token = 'ROLLBAR_TEST_TOKEN';

Rollbar::init(
    array(
        'access_token' => $token,
        'ignore_validation' => true,
        'environment' => 'production'
    )
);

function something() {
  somethingElse();
}

function somethingElse() {
  trigger_error("Oops!", E_USER_ERROR);
}

something();
```

This results in two items when run from the command line for Rollbar v1.3.5

```
E_USER_ERROR: Oops!: Oops!
1 File ".../phpbar/vendor/rollbar/rollbar/src/Rollbar.php" line 190 in Rollbar\DataBuilder::generateErrorWrapper
2 File ".../phpbar/vendor/rollbar/rollbar/src/Rollbar.php" line 145 in Rollbar\Rollbar::generateErrorWrapper
3 File ".../phpbar/vendor/rollbar/rollbar/src/DataBuilder.php" line 1001 in Rollbar\Rollbar::errorHandler
4 File ".../phpbar/rollbar.php" line 43 in trigger_error
5 File ".../phpbar/rollbar.php" line 39 in somethingElse
6 File ".../phpbar/rollbar.php" line 46 in something
```

```
E_USER_ERROR: Oops!: Oops!
1 File ".../phpbar/vendor/rollbar/rollbar/src/Rollbar.php" line 190 in Rollbar\DataBuilder::generateErrorWrapper
2 File ".../phpbar/vendor/rollbar/rollbar/src/Rollbar.php" line 167 in Rollbar\Rollbar::generateErrorWrapper
3 File ".../phpbar/vendor/rollbar/rollbar/src/DataBuilder.php" line 1001 in Rollbar\Rollbar::fatalHandler
```

So the first one is the complete stack trace and comes from the errorHandler that is set. The other stack comes from the fatalHandler that seems to run after the errorHandler.

Problems:

* If we only get the fatal error then the stack trace is missing all of the important code of mine that causes this
* The `fatalHandler` and `errorHandler` frames have filenames and line numbers that make no sense because the PHP backtrace object is:
```
array(3) {
    'function' =>
    string(12) "fatalHandler"
    'class' =>
    string(15) "Rollbar\Rollbar"
    'type' =>
    string(2) "::"
  }
```
which means that we use `$exception->getFile()` and `$exception->getLine()` which pulls the data from where the ErrorWrapper was constructed which is meaningless in this context.
* That we are showing the fatalHandler and ErrorWrapper frames at all is not helpful. This is just saying, yeah we caught it, it does not help for debugging. The downside being in the fatalHandler case if we got rid of those frames we would have an empty back trace.

**Comment by otang** [comment]
I'm also having an issue where the stacktrace is not helpful. 
![image](https://user-images.githubusercontent.com/800081/33498523-866bad92-d686-11e7-905c-1ea4e028d665.png)

Is it possible to see the line number where the error was triggered?

**Comment by ArturMoczulski** [comment]
@rokob in the example you provided there is actually an additional bug. The error is logged to Rollbar twice (through `Rollbar::errorHandler` and `Rollbar::fatalHandler`). This is caused by the list of fatal errors in https://github.com/rollbar/rollbar-php/blob/4637e6f3ee1218f902a39b4d942c596b3188e769/src/Rollbar.php#L12 being incorrect. `E_USER_ERROR` is not considered a fatal error in PHP. I resolved this.

Not I'm working on below.

> If we only get the fatal error then the stack trace is missing all of the important code of mine that causes this

In PHP the stack trace is cleared before the shutdown function is executed as per comments in the PHP manual:
http://php.net/manual/en/function.register-shutdown-function.php#95256
and Stackoverflow:
https://stackoverflow.com/questions/216963/fastest-way-to-determine-where-php-script-exits/216979#216979

In our case, `DataBuilder::generateErrorWrapper` is called in the registered shutdown function `Rollbar::fatalHandler`. On line https://github.com/rollbar/rollbar-php/blob/4637e6f3ee1218f902a39b4d942c596b3188e769/src/DataBuilder.php#L997 `debug_backtrace` return a stack trace of the shutdown function without the previous stack.

> That we are showing the fatalHandler and ErrorWrapper frames at all is not helpful. This is just saying, yeah we caught it, it does not help for debugging. The downside being in the fatalHandler case if we got rid of those frames we would have an empty back trace.

Yes, ideally we should remove this.

Right now, I'm focusing on including full stack traces for fatal errors.

**Comment by ArturMoczulski** [comment]
> The fatalHandler and errorHandler frames have filenames and line numbers that make no sense because the PHP backtrace object is (...)

I added this to address this issue https://github.com/rollbar/rollbar-php/issues/254

Fatal errors look like an edge-case scenario that I didn't consider before. My guess is that in case of fatal errors we should not be fetching file path and line number from the exception object.

**Comment by ArturMoczulski** [comment]
Here is a PR https://github.com/rollbar/rollbar-php/pull/302 that resolves all of the problems covered by this issue.
