### ISSUE TITLE
Allow >1.0 for monolog dependency

### ISSUE THREAD

**Issue by rtek** [rollbar/rollbar-php#460]
#432 was resolved in 889501d but caused #458 which was resolved in 8a57ad9.

Can you convert to a looser constraint such as >=1.0? Monolog 2.0 is beta so by default 1.0 will still take priority.

**Comment by jonnott** [comment]
+1 for allowing monolog 2.x support .. other dependencies in my projects require either monolog 1.x or 2.x, but I had to force them to require monolog 1.x so that v1.8.1 of this lib can be loaded rather than v1.8.0  (which is stated as broken, missing a 'critical fix').

Support for monolog 2.x in this lib would resolve all this nicely, with monolog 2.x be the used version.

**Comment by jonnott** [comment]
Bugsnag have already sorted this .. not looking good for Rollbar!

https://github.com/bugsnag/bugsnag-laravel/releases

**Comment by rtek** [comment]
Resolved in v2.0.0
