### ISSUE TITLE
Does rollbar-php require StreamHandler in monolog?

### ISSUE THREAD

**Issue by rnagatsukapmc** [rollbar/rollbar-php#495]
We are planing to use rollbar for our Wordpress sites, and realized that there's a security concern that one of its dependencies - monolog - executes `mkdir($dir, 0777, true);` in `Monolog\Handler\StreamHandler::createDir`. 

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L158

```
    private function createDir(): void
    {
        // Do not try to create dir if it has already been tried.
        if ($this->dirCreated) {
            return;
        }

        $dir = $this->getDirFromStream($this->url);
        if (null !== $dir && !is_dir($dir)) {
            $this->errorMessage = null;
            set_error_handler([$this, 'customErrorHandler']);
            $status = mkdir($dir, 0777, true);
            restore_error_handler();
            if (false === $status && !is_dir($dir)) {
                throw new \UnexpectedValueException(sprintf('There is no existing directory at "%s" and it could not be created: '.$this->errorMessage, $dir));
            }
        }
        $this->dirCreated = true;
    }

```
Would you be able to clarify that rollbar/rollbar-php doesn't require StreamHandler at all? I see in RollbarLogger.php that StreamHandler is declared but don't see it's actually being used. 
https://github.com/rollbar/rollbar-php/blob/master/src/RollbarLogger.php#L8 

Thanks!

**Comment by bishopb** [comment]
Mode `0777` is the [default for `mkdir`](https://www.php.net/manual/en/function.mkdir.php), so it's not without precedent. That said, you can configure the effective permissions through a `umask`. So one way to mitigate this would be, in your WordPress bootstrap, do:

```
umask(0077);
```

That's good security hygiene anyway, because one never knows (without thorough review) what libraries will do. That may have downstream effects, so to answer your question: I can't find any reference to Rollbar using `StreamHandler`, so I don't believe the code in question will not be executed.

Forensically, `StreamHandler` was added by commit ec15cb31b7 (Feb 5, 2018) then later removed by commit fd213eed (Aug 31, 2018) by the same author, @ArturMoczulski. Looks like the latter commit just missed this one declaration.

**Comment by rnagatsukapmc** [comment]
Thanks for the reply and clarification. I'll see if we can add umask as advised. In the meantime I submitted PR which removes StreamHandler from RollbarLogger.php. - https://github.com/rollbar/rollbar-php/pull/500 

Please take a look when you get a chance. Thanks!
