### ISSUE TITLE
Error: Class 'Rollbar\Response' not found

### ISSUE THREAD

**Issue by brainz80** [rollbar/rollbar-php#513]
```CurlSender.php``` threw ```Error: Class 'Rollbar\Response' not found``` on line 77.

I'm using rollbar-php version v2.1.0.

**Comment by bishopb** [comment]
Hi @brainz80, appreciate the report! In looking into this, I'm having difficulty reproducing. Here's what I'm seeing:

```
❯ git checkout tags/v2.1.0
HEAD is now at ff3db57 chore(2.1.0): release v2.1.0 (#493)

❯ nl -b a src/Senders/CurlSender.php | sed -n '1,10p; 73,80p;'
     1	<?php namespace Rollbar\Senders;
     2	
     3	/**
     4	 * Adapted from:
     5	 * https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer/Socket.php
     6	 */
     7	
     8	use Rollbar\Response;
     9	use Rollbar\Payload\Payload;
    10	use Rollbar\Payload\EncodedPayload;
    73	
    74	        $data = $payload->data();
    75	        $uuid = $data['data']['uuid'] ?? null;
    76	        
    77	        return new Response($statusCode, $result, $uuid);
    78	    }
    79	
    80	    public function sendBatch($batch, $accessToken)

❯ head -10 src/Response.php
<?php namespace Rollbar;

class Response
{
    private $status;
    private $info;
    private $uuid;

    public function __construct($status, $info, $uuid = null)
    {
    
❯ jq .autoload composer.json
{
  "psr-4": {
    "Rollbar\\": "src/"
  }
}
```

Line 77 from your original error report refers to the class name `Response`, which is qualified as being `Rollbar\Response` on line 10. That class name is defined in `src/Response.php`, and the composer PSR-4 autoloader is rigged so that `Rollbar\` namespace points to `src/`. Given these, I'd expect this code to work.

Looking at code coverage to see if we actually test this, I see we have numerous test cases that pass through this line:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/6844145/141485862-fea784e8-88e5-4524-b3a1-55e55974a141.png">

Given these facts, it seems like this might not be an issue in the `rollbar-php` code.

I would hazard a guess that perhaps your local autoloading mechanism may have had a bad cache entry or needed some other setup? I've certainly seen weird things like this when deploying new code.

I'm going to close this one now as non-reproducible, but if you can send some further details about your setup that can reproduce this, we'll be happy to continue investigating.

**Comment by brainz80** [comment]
@bishopb hi, thanks for checking it out. I'll have to check if the autoloading is somehow corrupted.
