### ISSUE TITLE
Version 0.16.0

### ISSUE THREAD

**Issue by chrisatomix** [rollbar/rollbar-php#87]
I'm seeing notifications for version 0.16.0 on Rollbar:
![image](https://cloud.githubusercontent.com/assets/1768449/14939910/ef77ee8a-0f9b-11e6-90a8-975a03e1afff.png)
However Github doesn't show 0.16.0 as released, the code still shows 0.15.0.
```php
class RollbarNotifier {
    const VERSION = "0.15.0";
```
The changelog doesn't show this either.

Is it safe or recommended to update to 0.16.0 and manually edit the rollbar.php file with the correct version number? Or should we just ignore the messages in our control panel?

Please make sure that Rollbar update notifications accurately reflect the latest released version, otherwise it's just creating unnecessary work for us.

**Comment by limenet** [comment]
I agree with @chrisatomix and have the same issue.

One question though: @chrisatomix what do you mean by
> However Github doesn't show 0.16.0 as released [...]

?
As far as I can see, version `0.16.0` has been released"(in this case using `git tag`) [on April 22, 2016](https://github.com/rollbar/rollbar-php/releases). And it also shows up on [Packagist](https://packagist.org/packages/rollbar/rollbar).

---

**To the package maintainer(s):**
In addition to what @chrisatomix wrote, please update your [changelog](https://github.com/rollbar/rollbar-php/blob/master/CHANGELOG.md) and/or use [releases](https://github.com/rollbar/rollbar-php/releases).

Since this package is still using a `0.x` version, it is [considered to be unstable by semver](http://semver.org/#spec-item-4). As an implication of this, developers (strictly speaking) cannot assume version `0.15.0` and `0.16.0` behave in the same way let alone have the same API. Instead the changelog has to be reviewed and if there's no changelog, individual commits have to be inspected. Only after that, they can upgrade to the new version.

Please bear this in mind when releasing new versions.

**Comment by chrisatomix** [comment]
I was going by the changelog file, which says "Next Release" (to me that suggests that it's still a work in progress).

**Comment by limenet** [comment]
I see, thanks, @chrisatomix

**Comment by Crisfole** [comment]
Hey there, my apologies. I'll get that updated later today.

**Comment by Crisfole** [comment]
Fixed in c62dcd4
