### ISSUE TITLE
Relase 0.17.0 has wrong version

### ISSUE THREAD

**Issue by frolof** [rollbar/rollbar-php#90]
Hey,
I noticed in rollbar panel I should update rollbar library. I updated but message didn't dissapeared. Then I discovered there is wrong version typed in release
https://github.com/rollbar/rollbar-php/blob/v0.17.0/src/rollbar.php#L93

**Comment by Crisfole** [comment]
Hey there! We definitely ought to automate this craziness! Thanks for the heads up. It'll be a bit before we get to this, but we'll fix!

**Comment by bkuhl** [comment]
Is it valuable to keep the version number in the class itself when it can be obtained from a `composer.lock` file?

**Comment by dlsteuer** [comment]
the `composer.lock` file contains the version of the dependencies, if I understand composer correctly, but not the library version, the version on packagist is driven by the tags on the github repo. I don't think this issue is useful anymore, since we've released additional updates since, I'm going to close it.
